### PR TITLE
Fix Issue 333 - Consistent Button Styling

### PR DESCRIPTION
**Pull request by dchen97**
Fix for Issue #333 
* Added explicit styling for select menus and buttons to make UI more consistent.

This is what the UI looks like right now:
image

### CODE REVIEW

**Comment by rabidbit** [comment]
Ooo... Nice! Like the overall look! In terms of color, however, would not use gray since it often implies a disabled feature/button. Can you make them white or a light, off-white color?

**Comment by rabidbit** [comment]
Adding @theresa-lee in case she has additional comments.

**Comment by dchen97** [comment]
OK I've changed the background colors of the buttons to be white. This is what the UI looks like now:

image

**Comment by rabidbit** [comment]
Let's not do a gray background color at all for controls (reserve that for disabled features). Instead, you could use a 1px gray border on hover.

In terms of the code, it looks like you are using a class called "blue". Convention is to prepend "tie-" to all classnames to avoid generic names. I see that you are using multi-class selectors for blue, but I'm inclined to stick with convention. What do you think @theresa-lee ?

**Comment by dchen97** [comment]
OK I've gotten rid of the gray background colors altogether and changed the `.blue` class to be `.tie-blue`. Below is a GIF showing what happens to each button on hover.

recording

**Comment by rabidbit** [comment]
LGTM! Thanks dchen97!

**Pull request merged**
