### PR TITLE
Refactor localStorage to be context-independent and use it for saving code and session history.

### PR DESCRIPTION
**Pull request by seanlip**

### CODE REVIEW

**Comment by eyurko** [comment]
Do you need me to take a look now or can it wait until Monday? Don't want to block you if you're in a groove.

**Comment by seanlip** [comment]
Monday's totally fine, thanks! This is the last PR for the session history / local storage refactor, so it's not blocking anything for now. I'll start work on the conversation flow next week.

**Comment by eyurko** [comment]
Awesome. Just wanted to make sure I'm being proactive. :)

**Comment by seanlip** [comment]
Thanks!

**Pull request merged**
