### PR TITLE
Fix #366: Change Button Control Styling in Dark Mode

### LINKED ISSUE #366: Buttons in dark mode are too bright

### PR DESCRIPTION
**Pull request by dchen97**
Fix to Issue #366 
* Changed styling in dark mode to make button controls not as bright
image

### CODE REVIEW

**Comment by rabidbit** [comment]
The button colors LGTM. Any chance you could also lighten the font colors for the footer links in night mode (make it stand out slightly more / lighter shade of gray?

**Comment by seanlip** [comment]
Code LGTM

**Comment by rabidbit** [comment]
LGTM! @theresa-lee does the css name convention look OK (not using 'tie-')? I have no strong opinions on it.

**Comment by rabidbit** [comment]
Nevermind (got OK from sll).

**Comment by dchen97** [comment]
OK! All of the CSS classes should look like .tie-*.night-mode now.

**Pull request merged**
