### PR TITLE
get question IDs from keys of question dict.

### PR DESCRIPTION
**Pull request by lk-chen**
A new key-value pair is added to globalData.questions in each &lt;question>.js file. Thus we can get the list of question IDs from keys of globalData.questions, I guess?

### CODE REVIEW

**Comment by lk-chen** [comment]
I just found out that there is a similar TODO for the same issue, in TaskSchemaValidationServiceSpec.js .

**Comment by seanlip** [comment]
Ah yep, @eyurko just noticed that too. Would you mind fixing that one too?

**Comment by lk-chen** [comment]
I have fixed it. Shall I put that commit in this same PR, or shall I open another PR?

**Comment by seanlip** [comment]
Another PR (and separate branch), please -- this one's already been merged. Thanks!

**Pull request merged**
