### PR TITLE
Add BuggyOutputFunction validation test / Fix BuggyOutputFunction error in isPalindrome.

### LINKED ISSUE #262: TaskSchemaValidation doesn't properly validate if function names appear in auxiliary code
See issue #261 

buggyFunctionName is AuxiliaryCode.forgetToIgnoreSpace, but forgetToIgnoreSpaces appears in the AuxiliaryCode, so this passes.

### PR DESCRIPTION
**Pull request by eyurko**
This fixes #262 and #261, and of course still contains all the garbage from #263.

Love GitHub, so much.

### CODE REVIEW

**Comment by seanlip** [comment]
So, this shouldn't have all the extra stuff. Can you do the following instead?

- do a fresh checkout and pull of the master branch
- create a new branch off of that
- do "git log" to verify that the last commit matches the one [here](https://github.com/google/tie/commits/master)
- make a commit there 
- push that branch

Thanks!

**Comment by seanlip** [comment]
Also, does this address #257?

**Comment by eyurko** [comment]
Nope, but I can fix that.

**Comment by eyurko** [comment]
Actually, it seems like it's a very different problem, so I'd prefer to have a different PR address that rather than conflating it with this one.

**Comment by seanlip** [comment]
Ah, ok with me. Just checking, since it seemed related.

**Pull request closed without merging**
