### PR TITLE
Button for resetting feedback

### PR DESCRIPTION
**Pull request by theresa-lee**
Added a button to reset the feedback window (it needs to be updated when the localstorage stuff is implemented).

### CODE REVIEW

**Comment by seanlip** [comment]
Hm, I'm slightly confused by this. I thought we were planning to have one button that resets (only) code, and nothing else? The issue is that the current button resets both.

**Comment by theresa-lee** [comment]
So I believe the decision from the feedback from users is that we would have two reset buttons, one for feedback and one for code. This PR adds in the one for feedback, and the current reset code button does indeed reset both code and feedeback because we don't have storing the feedback mechanisms in place.

So this isn't a PR to fix the current reset code button (which is admittedly buggy) but that would be something that would be fixed with the localStorage stuff being added.

Should we wait until after that has been submitted and integrated before adding in this button?

**Comment by seanlip** [comment]
Ah -- actually, I had thought the decision was to have one button that resets only the code, and to hold off on adding the "reset feedback" button until users find that they need it. I can't find the notes on this, though, so just to double check -- @rabidbit, do you remember which one it is?

**Comment by rabidbit** [comment]
Separating clearing code and clearing feedback functionality - definite yes.
Ability to clear code - definite yes.
Ability to clear feedback - slight yes; so, we can go either way and rely on future feedback to make adjustments. I'd say do what's best from two angles (a) easiest direction to revert in (b) least confusing from a UX standpoint (since enabling feedback would result in another button.
Ability to specify if feedback should be cleared before moving on to the next part of the question / prompt - definite yes.

**Comment by seanlip** [comment]
Hm, I'm slightly confused about the last two points:

> Ability to clear feedback - slight yes; so, we can go either way and rely on future feedback to make adjustments. I'd say do what's best from two angles (a) easiest direction to revert in (b) least confusing from a UX standpoint (since enabling feedback would result in another button).

This last part suggests having one button, I think (at least in the interim).

> Ability to specify if feedback should be cleared before moving on to the next part of the question / prompt - definite yes.

But this suggests having two buttons? Or do you mean: definite yes to actually clearing the feedback when moving between tasks/questions?

**Comment by rabidbit** [comment]
Whether there is a button to clear the feedback before moving on to the next task and how such a button is implemented is an open UI/UX question for the person implementing it (is it a checkmark in the "proceed to next question / question library" overlay? Is it a button within the overlay?). This is something users asked for; so, I think it should be done.

I'm making a distinction between this and the feature where the user can clear the feedback history at any time for any reason (which, if implemented, I would assume almost requires a separate button to clear). I think this is a separate feature where there was a slight preference to having this feature. Since it was slight in a small population set, I think it's up to us to decide (hence some of my thoughts on how to decide if we should do this or not), and we can adjust later as needed.

**Comment by theresa-lee** [comment]
Closing this because we decided that we would not have a reset feedback button unless user studies result in users asking for them.

**Pull request closed without merging**
